### ISSUE TITLE
Linebreaks after 'get' or 'set' in class bodies are not parsed correctly (T7533)

### ISSUE THREAD

**Issue by motiz88** [babel/babylon#157] opened 2016-10-05 10:54 UTC
> Issue originally made by @bakkot (as T7533 and later babel/babel#4432)
### Input code

```
class A {
  get
    x(){}
}
```
### Description

This code gives a parse error without the class-properties-transform plugin, and is parsed as a class containing a single method `x` with it. Neither is correct; it's valid syntax for a class with a getter (not method) for 'x'.

**Comment by motiz88** [comment] 2016-10-05 11:30
All parsers on ast-explorer.net, [except for TypeScript](https://astexplorer.net/#/TUQ7X6JE0X), disagree with [Babylon's](https://astexplorer.net/#/FfgQs2zhyt/1) parse here.

**Comment by bakkot** [comment] 2016-10-09 17:50
The issue is larger than I initially reported. All of the following are incorrectly rejected:

```js
class C {
  x
  (){}
}
```

```js
class C {
  ''
  (){}
}
```

```js
class C {
  ['']
  (){}
}
```

```js
class C {
  get
  (){}
}
```

```js
class C {
  set
  (){}
}
```

```js
class C {
  static
  (){}
}
```

```js
class C {
  async
  (){}
}
```

etc., which define methods named 'x', '', 'get', 'set', 'static', or 'async'.

**Comment by danez** [comment] 2017-06-03 09:52
Fixed as of 6.17.0

**Closed** 2017-06-03 09:56 UTC
Labels: bug
