### ISSUE TITLE
Error parsing a generator function with decorator

### ISSUE THREAD

**Issue by pwalczyszyn** [babel/babylon#382] opened 2017-02-24 09:54 UTC
Babylon parser fails when generator function is preceded with decorator.

### Input Code
```js
class MyClass {
  @MyDecorator
  *generatorFunction() {
  }
}
```

### Expected Behavior
This is valid JS so no error should be thrown.

### Current Behavior
Getting `Unexpected token`, below is stack trace:
```
   at Parser.pp$5.raise (/my-app-path/node_modules/babylon/lib/index.js:4373:13)
   at Parser.pp.unexpected (/my-app-path/node_modules/babylon/lib/index.js:1716:8)
   at Parser.pp$3.parseIdentifier (/my-app-path/node_modules/babylon/lib/index.js:4251:10)
   at Parser.pp$3.parsePropertyName (/my-app-path/node_modules/babylon/lib/index.js:4075:96)
   at Parser.parsePropertyName (/my-app-path/node_modules/babylon/lib/index.js:5999:23)
   at Parser.pp$1.parseClassBody (/my-app-path/node_modules/babylon/lib/index.js:2414:10)
   at Parser.pp$1.parseClass (/my-app-path/node_modules/babylon/lib/index.js:2361:8)
   at Parser.pp$1.parseExport (/my-app-path/node_modules/babylon/lib/index.js:2577:19)
   at Parser.parseExport (/my-app-path/node_modules/babylon/lib/index.js:5790:20)
   at Parser.pp$1.parseStatement (/my-app-path/node_modules/babylon/lib/index.js:1839:74)
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.16.1
| node             | 6.9.4
| npm              | 3.10.10
| Operating System | MacOS

**Comment by rattrayalex** [comment] 2017-04-07 22:16
Perhaps relatedly, computed methods with decorators also do not parse: 

```js
class X {
  @d
  ['m']() {}
}
```
gives `Unexpected token (3:10)`

(perhaps worth nothing that Flow's parser parses this incorrectly, but parses the decorated generator method correctly)

**Comment by bakkot** [comment] 2017-04-07 22:24
This issue looks like a dupe of https://github.com/babel/babylon/issues/13 (and @rattrayalex yours looks like a dupe of #33 / #232 / #231).

**Comment by rattrayalex** [comment] 2017-04-07 22:27
Yep, this looks closable to me as a dup

**Comment by hzoo** [comment] 2017-06-22 14:33
Closing as a dupe of https://github.com/babel/babylon/issues/13

**Closed by hzoo** 2017-06-22 14:33 UTC
Labels: bug, Spec: Decorators
