### ISSUE TITLE
Flow plugin throws syntax error for conditional expression

### ISSUE THREAD

**Issue by jj-choi** [babel/babylon#464] opened 2017-04-11 03:30 UTC
### Input Code

FAIL
```js
a ? (b => c) :  d => e  
```
SUCCESS
```js
a ?  b => c  :  d => e  
a ?  b => c  : (d => e) 
a ? (b => c) : (d => e) 
```

### Babylon/Babel Configuration

```js
{
  "plugin": [ "flow" ]
}
```

### Expected Behavior

Flow-parser(https://www.npmjs.com/package/flow-parser) output
```
ExpressionStatement (
  ConditionalExpressoin (
    test: Identifier('a'),
    consequent: ArrowFunctionExpression('b => c'),
    alternate: ArrowFunctionExpression('d => e')
  )
)
```
### Current Behavior

```
SyntaxError: test.js: Invalid left-hand side in arrow function parameters (1:5)
> 1 | a ? (b => c) : d => e
    |      ^
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.16.1
| node             | 6.10.2
| npm              | 3.10.10

**Comment by hzoo** [comment] 2017-04-11 03:30
Hey @jj-choi! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by danez** [comment] 2017-04-11 08:48
Thanks for reporting, this is a duplicate of #58

**Closed by danez** 2017-04-11 08:48 UTC
